name: "Build and Push docker images to GitHub Container Registry"

on:
    push: 
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build docker image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo 
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry 
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push image to private registry (GHCR)
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ghcr.io/${{github.actor}}/fast-api-crud:latest
                file: ./Dockerfile
                context: .